### ISSUE TITLE
Admin config error: Undefined index: id in Iterator.php on line 59

### ISSUE THREAD

**Issue by taqvi** [mageplaza/magento-2-better-popup#6]
Can anybody explain this issue:

1 exception(s):
Exception #0 (Exception): Notice: Undefined index: id in E:\Xampp\htdocs\magento_15\vendor\magento\module-config\Model\Config\Structure\Element\Iterator.php on line 59

Exception #0 (Exception): Notice: Undefined index: id in E:\Xampp\htdocs\magento_15\vendor\magento\module-config\Model\Config\Structure\Element\Iterator.php on line 59
#0 E:\Xampp\htdocs\magento_15\vendor\magento\module-config\Model\Config\Structure\Element\Iterator.php(59): Magento\Framework\App\ErrorHandler->handler(8, 'Undefined index...', 'E:\\Xampp\\htdocs...', 59, Array)
#1 E:\Xampp\htdocs\magento_15\vendor\magento\module-config\Model\Config\Structure.php(92): Magento\Config\Model\Config\Structure\Element\Iterator->setElements(Array, 'default')
#2 E:\Xampp\htdocs\magento_15\var\generation\Magento\Config\Model\Config\Structure\Interceptor.php(24): Magento\Config\Model\Config\Structure->getTabs()
#3 E:\Xampp\htdocs\magento_15\vendor\magento\module-config\Model\Config\Structure.php(135): Magento\Config\Model\Config\Structure\Interceptor->getTabs()
#4 E:\Xampp\htdocs\magento_15\var\generation\Magento\Config\Model\Config\Structure\Interceptor.php(63): Magento\Config\Model\Config\Structure->getFirstSection()
#5 E:\Xampp\htdocs\magento_15\vendor\magento\module-config\Controller\Adminhtml\System\AbstractConfig.php(57): Magento\Config\Model\Config\Structure\Interceptor->getFirstSection()
#6 E:\Xampp\htdocs\magento_15\vendor\magento\framework\Interception\Interceptor.php(74): Magento\Config\Controller\Adminhtml\System\AbstractConfig->dispatch(Object(Magento\Framework\App\Request\Http))
#7 E:\Xampp\htdocs\magento_15\vendor\magento\framework\Interception\Chain\Chain.php(70): Magento\Config\Controller\Adminhtml\System\Config\Index\Interceptor->___callParent('dispatch', Array)
#8 E:\Xampp\htdocs\magento_15\vendor\magento\framework\Interception\Chain\Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Config\\...', 'dispatch', Object(Magento\Config\Controller\Adminhtml\System\Config\Index\Interceptor), Array, 'adminAuthentica...')
#9 E:\Xampp\htdocs\magento_15\vendor\magento\module-backend\App\Action\Plugin\Authentication.php(143): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#10 E:\Xampp\htdocs\magento_15\vendor\magento\framework\Interception\Chain\Chain.php(67): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento\Config\Controller\Adminhtml\System\Config\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#11 E:\Xampp\htdocs\magento_15\vendor\magento\framework\Interception\Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Config\\...', 'dispatch', Object(Magento\Config\Controller\Adminhtml\System\Config\Index\Interceptor), Array, 'adminMassaction...')
#12 E:\Xampp\htdocs\magento_15\vendor\magento\module-backend\App\Action\Plugin\MassactionKey.php(33): Magento\Config\Controller\Adminhtml\System\Config\Index\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#13 E:\Xampp\htdocs\magento_15\vendor\magento\framework\Interception\Interceptor.php(142): Magento\Backend\App\Action\Plugin\MassactionKey->aroundDispatch(Object(Magento\Config\Controller\Adminhtml\System\Config\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#14 E:\Xampp\htdocs\magento_15\var\generation\Magento\Config\Controller\Adminhtml\System\Config\Index\Interceptor.php(39): Magento\Config\Controller\Adminhtml\System\Config\Index\Interceptor->___callPlugins('dispatch', Array, Array)
#15 E:\Xampp\htdocs\magento_15\vendor\magento\framework\App\FrontController.php(55): Magento\Config\Controller\Adminhtml\System\Config\Index\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#16 E:\Xampp\htdocs\magento_15\vendor\magento\framework\Interception\Interceptor.php(74): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#17 E:\Xampp\htdocs\magento_15\vendor\magento\framework\Interception\Chain\Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#18 E:\Xampp\htdocs\magento_15\vendor\magento\framework\Interception\Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#19 E:\Xampp\htdocs\magento_15\vendor\magento\framework\Module\Plugin\DbStatusValidator.php(69): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#20 E:\Xampp\htdocs\magento_15\vendor\magento\framework\Interception\Interceptor.php(142): Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#21 E:\Xampp\htdocs\magento_15\var\generation\Magento\Framework\App\FrontController\Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#22 E:\Xampp\htdocs\magento_15\vendor\magento\framework\App\Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#23 E:\Xampp\htdocs\magento_15\vendor\magento\framework\App\Bootstrap.php(258): Magento\Framework\App\Http->launch()
#24 E:\Xampp\htdocs\magento_15\index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#25 {main}

**Comment by AndreaRivadossi** [comment]
Hi, I had the same issue, the solution form me was to check if the Mageplaza_Core was enabled correctrly. Because in my case was disabled :(
